const WALKING_SPEED = 1;
const RUNNING_SPEED = 3;
const SCREEN_LEFT = 0;
const SCREEN_RIGHT = 1280;
const SCREEN_TOP = 0;
const SCREEN_BOTTOM = 720;
const MAIN_CHARACTER_SCALE = 2;
const MAIN_CHARACTER_SIZE = 16;
