const WALKING_SPEED = 0.5;
const RUNNING_SPEED = 1.2;
const SCREEN_LEFT = 0;
const SCREEN_RIGHT = 640;
const SCREEN_TOP = 0;
const SCREEN_BOTTOM = 360;
const MAIN_CHARACTER_SCALE = 1;
const MAIN_CHARACTER_SIZE = 16;
